### Filtering & Sorting Data - DataFrame 구현

#### 1) 식당데이터

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv')
df = pd.DataFrame(data)
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [19]:
# quantity컬럼 값이 3인 데이터를 추출하여 첫 5행 출력 구현
data = {}
for c in df.columns:
    data[c] = df[c]

df1 = pd.DataFrame(data)
df1[df1['quantity'] == 3].head()

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

In [21]:
# quantity, item_price 두개의 컬럼으로 구성된 새로운 데이터 프레임을 정의하라
columns = ['quantity', 'item_price']
index = range(4622)

df2 = pd.DataFrame(index= index, columns=columns)
df2

     quantity item_price
0         NaN        NaN
1         NaN        NaN
2         NaN        NaN
3         NaN        NaN
4         NaN        NaN
...       ...        ...
4617      NaN        NaN
4618      NaN        NaN
4619      NaN        NaN
4620      NaN        NaN
4621      NaN        NaN

[4622 rows x 2 columns]

In [22]:
df2['quantity'] = df['quantity']
df2['item_price'] = df['item_price']

In [23]:
df2

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

In [40]:
# item_price 컬럼의 달러표시 문자를 제거하고 float 타입으로 저장하여 new_price 컬럼에 저장하라
new_price = []
for p in df['item_price']:
    p = p.split('$')
    new_price.append(p[1])

In [41]:
new_price

['2.39 ',
 '3.39 ',
 '3.39 ',
 '2.39 ',
 '16.98 ',
 '10.98 ',
 '1.69 ',
 '11.75 ',
 '9.25 ',
 '9.25 ',
 '4.45 ',
 '8.75 ',
 '8.75 ',
 '11.25 ',
 '4.45 ',
 '2.39 ',
 '8.49 ',
 '8.49 ',
 '2.18 ',
 '8.75 ',
 '4.45 ',
 '8.99 ',
 '3.39 ',
 '10.98 ',
 '3.39 ',
 '2.39 ',
 '8.49 ',
 '8.99 ',
 '1.09 ',
 '8.49 ',
 '2.39 ',
 '8.99 ',
 '1.69 ',
 '8.99 ',
 '1.09 ',
 '8.75 ',
 '8.75 ',
 '4.45 ',
 '2.95 ',
 '11.75 ',
 '2.15 ',
 '4.45 ',
 '11.25 ',
 '11.75 ',
 '8.75 ',
 '10.98 ',
 '8.99 ',
 '3.39 ',
 '8.99 ',
 '3.99 ',
 '8.99 ',
 '2.18 ',
 '10.98 ',
 '1.09 ',
 '8.99 ',
 '2.39 ',
 '9.25 ',
 '11.25 ',
 '11.75 ',
 '2.15 ',
 '4.45 ',
 '9.25 ',
 '11.25 ',
 '8.75 ',
 '8.99 ',
 '8.99 ',
 '3.39 ',
 '8.99 ',
 '10.98 ',
 '8.99 ',
 '1.69 ',
 '8.99 ',
 '3.99 ',
 '8.75 ',
 '4.45 ',
 '8.75 ',
 '8.75 ',
 '2.15 ',
 '8.75 ',
 '11.25 ',
 '2.15 ',
 '9.25 ',
 '8.75 ',
 '8.75 ',
 '9.25 ',
 '8.49 ',
 '8.99 ',
 '1.09 ',
 '9.25 ',
 '2.95 ',
 '11.75 ',
 '11.75 ',
 '9.25 ',
 '11.75 ',
 '4.45 ',
 '9.25 ',
 '4.45 ',
 '11.75 ',
 '8.75 ',
 '8.75 ',
 '4.45 ',
 '8.99 ',
 '8.99 ',
 '3.99 ',
 '8.49 ',
 '3.39 ',
 '8.99 ',
 '1.09 ',
 '9.25 ',
 '4.45 ',
 '8.75 ',
 '2.95 ',
 '4.45 ',
 '2.39 ',
 '8.49 ',
 '8.99 ',
 '8.49 ',
 '1.09 ',
 '8.99 ',
 '3.99 ',
 '8.75 ',
 '9.25 ',
 '4.45 ',
 '11.25 ',
 '4.45 ',
 '8.99 ',
 '1.09 ',
 '9.25 ',
 '2.95 ',
 '4.45 ',
 '11.75 ',
 '4.45 ',
 '8.49 ',
 '2.39 ',
 '10.98 ',
 '22.50 ',
 '11.75 ',
 '4.45 ',
 '11.25 ',
 '4.45 ',
 '11.25 ',
 '4.45 ',
 '11.25 ',
 '11.25 ',
 '11.75 ',
 '9.25 ',
 '4.45 ',
 '11.48 ',
 '17.98 ',
 '1.69 ',
 '17.50 ',
 '4.45 ',
 '8.49 ',
 '2.39 ',
 '17.50 ',
 '4.45 ',
 '4.45 ',
 '11.25 ',
 '11.75 ',
 '10.98 ',
 '8.49 ',
 '10.98 ',
 '2.18 ',
 '11.48 ',
 '8.49 ',
 '2.39 ',
 '4.45 ',
 '11.25 ',
 '11.75 ',
 '8.75 ',
 '8.49 ',
 '2.18 ',
 '8.49 ',
 '3.39 ',
 '8.49 ',
 '8.99 ',
 '10.98 ',
 '11.48 ',
 '8.49 ',
 '1.09 ',
 '1.09 ',
 '9.25 ',
 '8.75 ',
 '2.95 ',
 '9.25 ',
 '4.45 ',
 '11.25 ',
 '11.48 ',
 '8.49 ',
 '8.49 ',
 '8.99 ',
 '2.39 ',
 '11.25 ',
 '8.75 ',
 '2.95 ',
 '1.09 ',
 '8.99 ',
 '8.49 ',
 '2.39 ',
 '10.98 ',
 '1.09 ',
 '3.99 ',
 '11.25 ',
 '8.75 ',
 '8.49 ',
 '3.39 ',
 '8.75 ',
 '9.25 ',
 '2.15 ',
 '11.25 ',
 '11.25 ',
 '11.25 ',
 '4.45 ',
 '22.50 ',
 '4.45 ',
 '11.75 ',
 '8.75 ',
 '17.50 ',
 '8.75 ',
 '9.25 ',
 '8.75 ',
 '2.15 ',
 '9.25 ',
 '4.30 ',
 '8.75 ',
 '11.25 ',
 '2.15 ',
 '8.99 ',
 '1.09 ',
 '8.99 ',
 '3.99 ',
 '8.75 ',
 '2.95 ',
 '2.95 ',
 '11.75 ',
 '5.90 ',
 '9.25 ',
 '9.25 ',
 '11.75 ',
 '9.25 ',
 '2.95 ',
 '17.50 ',
 '8.75 ',
 '9.25 ',
 '10.98 ',
 '8.99 ',
 '1.09 ',
 '1.09 ',
 '1.09 ',
 '8.99 ',
 '10.98 ',
 '1.09 ',
 '8.75 ',
 '8.75 ',
 '9.25 ',
 '9.25 ',
 '8.75 ',
 '8.75 ',
 '8.99 ',
 '8.99 ',
 '8.99 ',
 '1.09 ',
 '11.75 ',
 '1.25 ',
 '8.99 ',
 '2.39 ',
 '9.25 ',
 '2.95 ',
 '8.99 ',
 '3.99 ',
 '8.49 ',
 '2.39 ',
 '8.49 ',
 '8.49 ',
 '8.49 ',
 '1.69 ',
 '8.49 ',
 '3.99 ',
 '8.99 ',
 '1.69 ',
 '1.09 ',
 '23.78 ',
 '17.50 ',
 '2.15 ',
 '8.75 ',
 '9.25 ',
 '9.25 ',
 '8.75 ',
 '4.45 ',
 '8.75 ',
 '11.25 ',
 '11.25 ',
 '1.25 ',
 '9.25 ',
 '4.45 ',
 '11.25 ',
 '11.75 ',
 '11.75 ',
 '6.49 ',
 '8.99 ',
 '2.39 ',
 '8.49 ',
 '2.39 ',
 '11.25 ',
 '8.75 ',
 '2.15 ',
 '8.99 ',
 '1.69 ',
 '8.75 ',
 '11.25 ',
 '2.15 ',
 '4.45 ',
 '8.75 ',
 '8.49 ',
 '8.99 ',
 '17.50 ',
 '8.49 ',
 '1.09 ',
 '1.09 ',
 '8.75 ',
 '1.25 ',
 '2.15 ',
 '11.08 ',
 '8.49 ',
 '8.49 ',
 '8.99 ',
 '2.39 ',
 '8.75 ',
 '2.15 ',
 '1.50 ',
 '11.25 ',
 '2.15 ',
 '8.49 ',
 '8.49 ',
 '11.75 ',
 '9.25 ',
 '11.75 ',
 '1.25 ',
 '11.25 ',
 '8.75 ',
 '4.45 ',
 '6.49 ',
 '9.25 ',
 '2.95 ',
 '11.25 ',
 '4.45 ',
 '1.25 ',
 '1.25 ',
 '8.49 ',
 '2.39 ',
 '2.18 ',
 '8.49 ',
 '2.18 ',
 '22.16 ',
 '17.50 ',
 '8.75 ',
 '2.95 ',
 '6.49 ',
 '8.99 ',
 '3.39 ',
 '3.39 ',
 '8.99 ',
 '8.49 ',
 '11.25 ',
 '2.15 ',
 '11.25 ',
 '2.95 ',
 '11.25 ',
 '1.25 ',
 '8.99 ',
 '1.09 ',
 '8.75 ',
 '8.75 ',
 '9.25 ',
 '2.95 ',
 '11.75 ',
 '1.50 ',
 '8.99 ',
 '1.09 ',
 '11.25 ',
 '1.25 ',
 '1.25 ',
 '11.25 ',
 '11.75 ',
 '2.15 ',
 '8.99 ',
 '1.69 ',
 '11.75 ',
 '6.49 ',
 '8.75 ',
 '9.25 ',
 '11.25 ',
 '4.45 ',
 '1.25 ',
 '11.25 ',
 '4.45 ',
 '8.49 ',
 '8.99 ',
 '8.49 ',
 '8.99 ',
 '11.25 ',
 '1.25 ',
 '11.75 ',
 '1.25 ',
 '11.75 ',
 '9.25 ',
 '4.45 ',
 '11.25 ',
 '2.15 ',
 '32.94 ',
 '1.25 ',
 '11.25 ',
 '11.48 ',
 '1.69 ',
 '1.09 ',
 '17.50 ',
 '4.45 ',
 '6.49 ',
 '9.25 ',
 '8.75 ',
 '9.25 ',
 '9.25 ',
 '8.75 ',
 '8.75 ',
 '2.15 ',
 '2.95 ',
 '17.50 ',
 '10.98 ',
 '11.48 ',
 '11.48 ',
 '3.39 ',
 '8.99 ',
 '1.69 ',
 '8.99 ',
 '1.09 ',
 '10.98 ',
 '3.39 ',
 '8.99 ',
 '1.09 ',
 '9.25 ',
 '8.75 ',
 '11.25 ',
 '4.45 ',
 '2.95 ',
 '9.25 ',
 '22.20 ',
 '8.49 ',
 '8.99 ',
 '8.75 ',
 '8.75 ',
 '11.75 ',
 '8.75 ',
 '11.25 ',
 '9.25 ',
 '11.25 ',
 '11.25 ',
 '8.75 ',
 '11.25 ',
 '2.95 ',
 '1.25 ',
 '8.49 ',
 '1.69 ',
 '11.75 ',
 '11.25 ',
 '8.75 ',
 '8.75 ',
 '4.45 ',
 '8.49 ',
 '3.99 ',
 '8.49 ',
 '3.99 ',
 '11.48 ',
 '1.69 ',
 '1.09 ',
 '11.25 ',
 '1.50 ',
 '10.58 ',
 '1.69 ',
 '9.25 ',
 '11.25 ',
 '8.75 ',
 '9.25 ',
 '11.25 ',
 '11.25 ',
 '8.75 ',
 '11.75 ',
 '8.75 ',
 '8.75 ',
 '8.75 ',
 '2.15 ',
 '11.25 ',
 '11.75 ',
 '2.50 ',
 '4.45 ',
 '9.25 ',
 '4.45 ',
 '11.25 ',
 '8.49 ',
 '3.99 ',
 '9.25 ',
 '9.25 ',
 '11.25 ',
 '9.25 ',
 '11.75 ',
 '11.25 ',
 '1.25 ',
 '23.50 ',
 '1.25 ',
 '8.99 ',
 '8.49 ',
 '7.40 ',
 '7.40 ',
 '8.75 ',
 '1.25 ',
 '4.45 ',
 '8.75 ',
 '2.15 ',
 '8.75 ',
 '4.45 ',
 '7.40 ',
 '7.40 ',
 '7.40 ',
 '8.99 ',
 '3.99 ',
 '8.99 ',
 '1.69 ',
 '8.75 ',
 '8.75 ',
 '8.75 ',
 '8.75 ',
 '11.25 ',
 '11.25 ',
 '2.95 ',
 '8.75 ',
 '18.50 ',
 '8.49 ',
 '3.99 ',
 '2.95 ',
 '9.25 ',
 '9.25 ',
 '3.00 ',
 '1.25 ',
 '8.75 ',
 '9.25 ',
 '4.45 ',
 '8.75 ',
 '11.25 ',
 '4.45 ',
 '10.98 ',
 '22.16 ',
 '4.45 ',
 '8.75 ',
 '9.25 ',
 '6.49 ',
 '9.25 ',
 '11.25 ',
 '8.75 ',
 '9.25 ',
 '2.15 ',
 '9.25 ',
 '4.45 ',
 '9.25 ',
 '2.95 ',
 '9.25 ',
 '8.75 ',
 '9.25 ',
 '1.25 ',
 '1.25 ',
 '8.75 ',
 '8.75 ',
 '9.25 ',
 '4.45 ',
 '11.75 ',
 '11.75 ',
 '11.75 ',
 '9.25 ',
 '9.25 ',
 '16.98 ',
 '2.39 ',
 '3.39 ',
 '3.39 ',
 '9.25 ',
 '11.75 ',
 '11.25 ',
 '2.15 ',
 '8.75 ',
 '9.25 ',
 '4.45 ',
 '10.98 ',
 '11.25 ',
 '9.25 ',
 '22.50 ',
 '9.25 ',
 '2.95 ',
 '1.50 ',
 '11.48 ',
 '8.49 ',
 '1.69 ',
 '8.49 ',
 '8.49 ',
 '8.49 ',
 '6.78 ',
 '11.75 ',
 '4.45 ',
 '8.75 ',
 '4.45 ',
 '11.89 ',
 '9.39 ',
 '8.75 ',
 '2.95 ',
 '1.25 ',
 '9.25 ',
 '8.75 ',
 '23.78 ',
 '8.75 ',
 '9.25 ',
 '2.15 ',
 '2.15 ',
 '1.25 ',
 '8.49 ',
 '3.99 ',
 '10.98 ',
 '1.09 ',
 '8.75 ',
 '4.45 ',
 '8.75 ',
 '11.75 ',
 '2.95 ',
 '4.45 ',
 '9.25 ',
 '8.75 ',
 '8.49 ',
 '3.99 ',
 '22.50 ',
 '11.25 ',
 '1.25 ',
 '8.75 ',
 '8.75 ',
 '18.50 ',
 '6.49 ',
 '8.75 ',
 '8.75 ',
 '4.45 ',
 '8.49 ',
 '3.99 ',
 '8.99 ',
 '1.09 ',
 '8.49 ',
 '2.39 ',
 '11.48 ',
 '1.69 ',
 '2.50 ',
 '9.25 ',
 '1.50 ',
 '17.50 ',
 '2.95 ',
 '8.75 ',
 '4.45 ',
 '11.75 ',
 '8.75 ',
 '8.49 ',
 '1.69 ',
 '8.49 ',
 '3.99 ',
 '8.99 ',
 '8.99 ',
 '3.99 ',
 '8.99 ',
 '11.25 ',
 '4.45 ',
 '1.25 ',
 '3.99 ',
 '10.98 ',
 '7.40 ',
 '3.00 ',
 '7.40 ',
 '4.00 ',
 '8.49 ',
 '3.99 ',
 '9.25 ',
 '4.45 ',
 '11.25 ',
 '1.25 ',
 '11.75 ',
 '1.25 ',
 '11.25 ',
 '2.15 ',
 '11.25 ',
 '4.45 ',
 '3.75 ',
 '11.75 ',
 '8.99 ',
 '2.39 ',
 '8.75 ',
 '4.45 ',
 '1.25 ',
 '8.99 ',
 '8.49 ',
 '2.18 ',
 '8.49 ',
 '2.18 ',
 '1.09 ',
 '8.75 ',
 '2.95 ',
 '1.25 ',
 '1.50 ',
 '11.25 ',
 '9.25 ',
 '2.95 ',
 '1.25 ',
 '8.49 ',
 '3.99 ',
 '11.48 ',
 '3.99 ',
 '8.49 ',
 '11.25 ',
 '1.25 ',
 '8.99 ',
 '1.69 ',
 '11.25 ',
 '1.25 ',
 '6.49 ',
 '8.75 ',
 '9.25 ',
 '8.75 ',
 '2.95 ',
 '8.75 ',
 '11.75 ',
 '8.69 ',
 '8.69 ',
 '2.29 ',
 '3.99 ',
 '8.49 ',
 '8.75 ',
 '8.75 ',
 '1.25 ',
 '11.75 ',
 '11.25 ',
 '11.25 ',
 '11.25 ',
 '1.25 ',
 '9.25 ',
 '11.75 ',
 '6.49 ',
 '3.99 ',
 '8.49 ',
 '11.25 ',
 '2.15 ',
 '11.25 ',
 '11.89 ',
 '8.99 ',
 '1.69 ',
 '8.99 ',
 '8.99 ',
 '3.99 ',
 '8.99 ',
 '9.25 ',
 '9.25 ',
 '2.15 ',
 '7.40 ',
 '7.40 ',
 '8.75 ',
 '8.75 ',
 '9.25 ',
 '4.45 ',
 '11.25 ',
 '1.25 ',
 '11.75 ',
 '11.25 ',
 '1.25 ',
 '3.99 ',
 '8.49 ',
 '8.49 ',
 '8.49 ',
 '8.99 ',
 '8.75 ',
 '2.15 ',
 '1.25 ',
 '8.49 ',
 '1.09 ',
 '1.09 ',
 '8.75 ',
 '2.95 ',
 '1.25 ',
 '9.25 ',
 '1.25 ',
 '2.15 ',
 '11.25 ',
 '1.25 ',
 '4.45 ',
 '8.75 ',
 '2.50 ',
 '8.90 ',
 '8.75 ',
 '8.75 ',
 '8.75 ',
 '11.25 ',
 '11.25 ',
 '10.98 ',
 '3.99 ',
 '10.98 ',
 '3.99 ',
 '1.69 ',
 '8.99 ',
 '9.25 ',
 '8.75 ',
 '8.99 ',
 '1.09 ',
 '9.25 ',
 '2.95 ',
 '8.75 ',
 '9.25 ',
 '3.99 ',
 '8.49 ',
 '8.75 ',
 '8.75 ',
 '22.50 ',
 '10.98 ',
 '3.27 ',
 '3.99 ',
 '8.99 ',
 '1.09 ',
 '11.08 ',
 '8.75 ',
 '4.45 ',
 '11.08 ',
 '3.99 ',
 '8.49 ',
 '4.30 ',
 '9.25 ',
 '8.75 ',
 '11.25 ',
 '11.25 ',
 '9.25 ',
 '8.49 ',
 '8.99 ',
 '8.49 ',
 '8.75 ',
 '2.95 ',
 '4.45 ',
 '9.25 ',
 '2.95 ',
 '9.25 ',
 '8.75 ',
 '11.25 ',
 '4.45 ',
 '16.98 ',
 '8.49 ',
 '2.39 ',
 '11.25 ',
 '3.75 ',
 '9.25 ',
 '4.45 ',
 '9.25 ',
 '9.25 ',
 '4.45 ',
 '8.75 ',
 '9.25 ',
 '8.75 ',
 '9.25 ',
 '9.25 ',
 '9.25 ',
 '11.48 ',
 '8.99 ',
 '22.50 ',
 '11.75 ',
 '11.25 ',
 '1.25 ',
 '8.75 ',
 '2.15 ',
 '1.25 ',
 '11.25 ',
 '8.75 ',
 '1.25 ',
 '11.25 ',
 '1.50 ',
 '11.25 ',
 '11.25 ',
 '9.25 ',
 '6.49 ',
 '8.90 ',
 '8.75 ',
 '4.45 ',
 '11.25 ',
 '1.25 ',
 '17.50 ',
 '9.25 ',
 '8.75 ',
 '11.75 ',
 '3.00 ',
 '8.49 ',
 '8.49 ',
 '10.98 ',
 '8.99 ',
 '3.99 ',
 '8.75 ',
 '4.45 ',
 '8.99 ',
 '1.69 ',
 '11.75 ',
 '8.75 ',
 '11.25 ',
 '4.45 ',
 '11.75 ',
 '1.25 ',
 '11.75 ',
 '2.95 ',
 '8.99 ',
 '8.99 ',
 '2.18 ',
 '17.98 ',
 '8.99 ',
 '8.49 ',
 '1.69 ',
 '11.75 ',
 '11.25 ',
 '2.95 ',
 '3.75 ',
 '9.25 ',
 '11.75 ',
 '8.75 ',
 '2.15 ',
 '1.50 ',
 '8.49 ',
 '8.49 ',
 '3.39 ',
 '8.69 ',
 '3.89 ',
 '8.75 ',
 '4.45 ',
 '8.75 ',
 '11.25 ',
 '2.15 ',
 '8.75 ',
 '8.49 ',
 '1.69 ',
 '8.49 ',
 '8.49 ',
 '1.25 ',
 '8.75 ',
 '11.75 ',
 '11.75 ',
 '8.99 ',
 '1.09 ',
 '8.75 ',
 '4.45 ',
 '8.75 ',
 '2.95 ',
 '8.75 ',
 '2.15 ',
 '3.99 ',
 '8.49 ',
 '8.99 ',
 '3.99 ',
 '8.49 ',
 '1.69 ',
 '1.09 ',
 '8.99 ',
 '1.09 ',
 '9.25 ',
 '8.75 ',
 '8.99 ',
 '2.39 ',
 '1.25 ',
 '1.25 ',
 '11.25 ',
 '11.25 ',
 '9.25 ',
 '9.25 ',
 '11.25 ',
 '1.50 ',
 '3.99 ',
 '8.49 ',
 '11.25 ',
 '9.25 ',
 '11.25 ',
 '17.50 ',
 '8.75 ',
 '8.90 ',
 '8.75 ',
 '8.75 ',
 '8.99 ',
 '2.39 ',
 '11.25 ',
 '9.25 ',
 '2.15 ',
 '11.25 ',
 '1.25 ',
 '11.75 ',
 '1.25 ',
 '11.25 ',
 '11.75 ',
 '1.25 ',
 '11.25 ',
 '11.25 ',
 '8.49 ',
 '10.98 ',
 '8.75 ',
 '1.25 ',
 '8.75 ',
 ...]

In [42]:
df['new_price'] = new_price

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
 5   new_price           4622 non-null   object
dtypes: int64(2), object(4)
memory usage: 216.8+ KB

In [45]:
df['new_price'] = df['new_price'].astype('float')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
 5   new_price           4622 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 216.8+ KB

In [ ]:
# item_name명이 Chicken Salad Bowl 인 데이터 프레임을 추출하라고 index 값을 초기화 하여라